#!/usr/bin/env ruby

vendor_path = "/../vendor/{gems,plugins}/cucumber*/bin/cucumber"
vendor_bin  = Dir["#{File.dirname(__FILE__)}#{vendor_path}"].first
if vendor_bin
  load File.expand_path(vendored_cucumber_bin)
else
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'cucumber'
  load Cucumber::BINARY
end
